version: '3.4'

services:
  neredekal.hotelservices.api:
    image: ${DOCKER_REGISTRY-}neredekalhotelservicesapi
    build:
      context: .
      dockerfile: NeredeKal.HotelServices.API/Dockerfile

    environment:
      - ASPNETCORE_ENVIRONMENT=Development 
      - "ConnectionStrings__DevelopmentDbConnection=host=stackupPostgres;Port=5432;Database=postgres;User Id=admin;Password=admin;"

  stackupPostgres:
    image: postgres
    container_name: stackupPostgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=stackup_postgress
    volumes:
      - stackup_postgres_data:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:6.17
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8009:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  stackupRedis:
    image: redis:alpine
    container_name: stackupRedis
    restart: always
    ports:
      - "6379:6379"

volumes:
  stackup_postgres_data:
  pgadmin-data: