version: '3.4'

services:

  neredekal.hotelservices.api:
    image: ${DOCKER_REGISTRY-}neredekalhotelservicesapi
    build:
      context: .
      dockerfile: NeredeKal.HotelServices.API/Dockerfile

    environment:
      - ASPNETCORE_ENVIRONMENT=Development 
      - "ConnectionStrings__DevelopmentDbConnection=host=stackupPostgres;Port=5432;Database=postgres;User Id=admin;Password=admin;"
      - "ElasticConfiguration__Uri=http://localhost:9200"
      - "RedisConfiguration__Uri=stackupRedis:6379"

  stackupPostgres:
    image: postgres
    container_name: stackupPostgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=stackup_postgress
    volumes:
      - stackup_postgres_data:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:6.17
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8009:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  #stackupRedis:
  #  image: redis:alpine
  #  container_name: stackupRedis
  #  restart: always
  #  ports:
  #    - "6379:6379"

  elasticsearch:
   container_name: elasticsearch
   image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
   ports:
    - 9200:9200
   volumes:
    - elasticsearch-data:/usr/share/elasticsearch/data
   environment:
    - xpack.monitoring.enabled=true
    - xpack.watcher.enabled=false
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    - discovery.type=single-node
    - cluster.name=proj-docker-cluster
    - bootstrap.memory_lock=false
   networks:
    - elastic  
   ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
   container_name: kibana
   image: docker.elastic.co/kibana/kibana:7.9.2
   ports:
    - 5601:5601
   depends_on:
    - elasticsearch
   environment:
    - ELASTICSEARCH_URL=http://localhost:9200
   networks:
    - elastic

volumes:
  stackup_postgres_data:
  pgadmin-data:
  elasticsearch-data:

networks:
  elastic:
    driver: bridge